
{
 'SCRIPT_NAME' => '',
  'PATH_INFO' => '/data/feed/api/user/brad.gushue/albumid/9810315389720904593',
  'REQUEST_METHOD' => 'POST',
  'HTTP_ACCEPT' => 'text/html, text/*;q=0.9, image/jpeg;q=0.9, image/png;q=0.9, image/*;q=0.9, */*;q=0.8',
  'SCRIPT_FILENAME' => '/home/mdupont/experiments/photo/photo-librarian-server/Photo-Librarian-Server/public/dispatch.cgi',
  'SERVER_SOFTWARE' => 'Apache/2.2.22 (Ubuntu)',
  'QUERY_STRING' => '',
  'REMOTE_PORT' => '44457',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux i686) KHTML/4.8.4 (like Gecko) Konqueror/4.8',
  'SERVER_SIGNATURE' => '<address>Apache/2.2.22 (Ubuntu) Server at picasaweb.google.com Port 80</address>
[Tue Sep 18 08:47:38 2012] [error] [client 127.0.0.1] ',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9',
  'CONTENT_TYPE' => 'multipart/related; boundary=----------SFP876ns5iH3IQ3gRB2L4sYkgqXvTUcth0zo6mfBSuCkLGRmRR5TKbC',
  'PATH' => '/usr/local/bin:/usr/bin:/bin',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SCRIPT_URL' => '/data/feed/api/user/brad.gushue/albumid/9810315389720904593',
  'DOCUMENT_ROOT' => '/home/mdupont/experiments/photo/photo-librarian-server/Photo-Librarian-Server/public/',
  'PATH_TRANSLATED' => '/home/mdupont/experiments/photo/photo-librarian-server/Photo-Librarian-Server/public/dispatch.cgi/data/feed/api/user/brad.gushue/albumid/9810315389720904593',
  'SERVER_NAME' => 'picasaweb.google.com',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, x-gzip, x-deflate',
  'SERVER_ADMIN' => '[no address given]',
  'HTTP_CONNECTION' => 'keep-alive',
  'SCRIPT_URI' => 'http://picasaweb.google.com/data/feed/api/user/brad.gushue/albumid/9810315389720904593',
  'CONTENT_LENGTH' => '673605',
  'HTTP_ACCEPT_CHARSET' => 'iso-8859-1,*;q=0.5',
  'redirect_carefully' => '1',
  'SERVER_PORT' => '80',
  'REMOTE_ADDR' => '127.0.0.1',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_URI' => '/data/feed/api/user/brad.gushue/albumid/9810315389720904593',
  'SERVER_ADDR' => '127.0.0.1',
  'HTTP_MIME_VERSION' => '1.0',
  'HTTP_HOST' => 'picasaweb.google.com'
};
